; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24213.1 

    TITLE	D:\Assembly\Hello.c
    .686P
    .XMM
    include listing.inc
    .model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_c$ = -12						; size = 4
_b$ = -8						; size = 4
_a$ = -4						; size = 4
_main	PROC
; File d:\assembly\hello.c
; Line 4
    push	ebp
    mov	ebp, esp
    sub	esp, 12					; 0000000cH
; Line 5
    mov	DWORD PTR _a$[ebp], 1
; Line 6
    mov	DWORD PTR _b$[ebp], 2
; Line 7
    mov	eax, DWORD PTR _a$[ebp]
    add	eax, DWORD PTR _b$[ebp]
    mov	DWORD PTR _c$[ebp], eax
; Line 8
    xor	eax, eax
; Line 9
    mov	esp, ebp
    pop	ebp
    ret	0
_main	ENDP
_TEXT	ENDS
END
